[options]
; قاعدة البيانات
db_host = odoo-postgres-87877258.hosted.cumin.dev
db_port = 5432
db_user = postgres
db_password = Smart-Phone
db_name = odoo  ; أو اسم القاعدة اللي بدك تستخدمها

; مسار الـ addons المخصصين
addons_path = /mnt/extra-addons

; خيارات Odoo أساسية
admin_passwd = admin123  ; كلمة مرور مدير Odoo (غيرها لو بدك)
xmlrpc_port = 8069
logfile = /var/lib/odoo/odoo.log

