[options]
db_host = postgres-5e96b27bd731
db_port = 5432
db_user = postgres
db_password = password

addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

admin_passwd = admin123
xmlrpc_port = 8069
proxy_mode = True
list_db = True